### ISSUE TITLE
Frame rate?

### ISSUE THREAD

**Issue by antithing** [dansim-umich/ORB_SLAM2_Bilateral_LoFTR#1]
Hi, and thank you for making this code available. Could you please share the frame rate that you are seeing with your additions? 

Is it possible to run at 50Hz?

Thanks!

**Comment by dansim-umich** [comment]
With the bilateral filter we were able to process about one frame every 0.109 seconds and with LoFTR every 13.105 seconds, which if I am understanding correctly would put this at 9.2 and 0.08 Hz respectively. This may be different on higher-end computers, as even without modifications we were only able to run ORB-SLAM2 at 34Hz.

This code is not able to run quickly at this time.

**Comment by antithing** [comment]
Understood, thank you for getting back to me!
